### PR TITLE
feat: themable Presenter

### PR DESCRIPTION
**Pull request by codepunkt**
PR for issue #365

### CODE REVIEW

**Comment by codepunkt** [comment]
Basically:
- `theme` is now assembled in `MDXDeck` and passed as a prop to `Provider`.
- `getWrapper` helper method is moved into `MDXDeck` render method because it needs access to the `theme`
- `Clock` component is exported by `@mdx-deck/components` in order to not have to import it from `@mdx-deck/components/src/Clock` when reusing it in custom `Presenter` components.

**Comment by alpinegizmo** [comment]
+1

Was thinking of doing roughly this myself. The current Presenter doesn't meet my needs, but there probably isn't one best path forward. Give me a clean way to rearrange it myself w/o forking and I'll be happy.

**Comment by pomber** [comment]
hey @jxnblk, any chances to merge this soon? I'm planning to release a new version of code surfer and this would allow me to add a custom presenter too (something like [this](https://twitter.com/pomber/status/1124662753753477120)). 
If you are busy with other projects don't worry, it can wait :raised_hands:

**Comment by jxnblk** [comment]
Sorry for the delay on this! Looks like this works – I think some of the logic in MDXDeck could be refactored into a hook or other utility later, but I think this is good to :shipit:

**Pull request merged**
