### PR TITLE
Pin Gatsby version

### LINKED ISSUE #595: Dev build fails when rebuilding presentation
Hello!  I have a very simple presentation that builds successfully the first time, but then fails to rebuild once a change is made.  If you simply save the file, the build does not fail, but any modification results in the following error:

```
Error: Command failed with exit code 1 (EPERM): gatsby develop --host localhost --port 8000 --open
    at makeError (/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/app/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The code is running within a docker container.  Here's the docker-compose file:

```
version: "3.6"
services:
    present:
        image: node
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        working_dir: /app
        entrypoint: ["npm"]
        command: ["start"]
    npm:
        image: node
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: ["npm"]
        command: ["--version"]
```

The `present` service issues the following `npm` command as defined in the "package.json" file:

```
"start": "mdx-deck presentation.mdx"
```

The actual presentation, saved as "presentation.mdx", is as follows:

```
# Presentation Title

---

# About Me
````

Here's how to setup and reproduce the issue (docker commands are run with `sudo` on my machine):

1. Install the framework: `docker-compose run --rm npm i -D mdx-deck`
1. Run the presentation service: `docker-compose run --rm --service-ports present`
1. The build will finish and you can see the presentation in the browser of the host
1. Save the "presentation.mdx" file without making any modifications
1. Notice that the `info` statement is logged, but the service remains stable
1. Modify the "presentation.mdx" file and save
1. The error mentioned above appears and the docker service dies

I noticed issue #416 which had a very similar error, but the "package-lock.json" file shows the `gatsby-plugin-compile-es6-packages` package as being installed at version "2.1.0".

### LINKED ISSUE #598: mdx-deck start error with 'TypeError: Cannot read property 'internal' of null'
I'm creating a deck using the example from Zeit's [now-examples](https://github.com/zeit/now-examples/tree/master/mdx-deck) repository.

I can start a development server correctly and see the `success: Building development bundle` output from Gatsby, however as soon as I change a file the development server crashes with this error:

```
  TypeError: Cannot read property 'internal' of null
  
  - gen-mdx.js:48 payloadCacheKey
    [javascript-slides]/[gatsby-plugin-mdx]/utils/gen-mdx.js:48:46
  
  - gen-mdx.js:51 genMDX
    [javascript-slides]/[gatsby-plugin-mdx]/utils/gen-mdx.js:51:43
  
  - source-nodes.js:108 processMDX
    [javascript-slides]/[gatsby-plugin-mdx]/gatsby/source-nodes.js:108:5
  
  - source-nodes.js:158 resolve
    [javascript-slides]/[gatsby-plugin-mdx]/gatsby/source-nodes.js:158:35
  
  - gatsby-node.js:40 
    [javascript-slides]/[gatsby-theme-mdx-deck]/gatsby-node.js:40:24
  
  - gatsby-node.js:47 resolveTitle
    [javascript-slides]/[gatsby-theme-mdx-deck]/gatsby-node.js:47:60
  

not finished createPages - 0.077s


——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
3 pages                                                                    In Progress                                                                    mdx-deck
Error: Command failed with exit code 1 (EPERM): gatsby develop --host localhost --port 8000 --open
    at makeError (/Users/jackleslie/Desktop/Talks/javascript-slides/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/jackleslie/Desktop/Talks/javascript-slides/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

[Here's my project](https://github.com/jackleslie/javascript-slides) for reference, nothing much to see at the moment

### PR DESCRIPTION
**Pull request by karlhorky**
Seems like for such a big dep as Gatsby, pinned versions are better (CRA / Next.js philosophy)

Fixes #595
Fixes #598

I think pinning the version would be a good best practice anyway, because of the frequent instabilities with Gatsby versions, such as #151.

### CODE REVIEW

**Comment by trevordmiller** [comment]
This would be very helpful to prevent the issues we've been having

**Comment by karlhorky** [comment]
jxnblk closed the underlying issue in #631, but I think pinning the version would be a good best practice anyway, because of the frequent instabilities with Gatsby versions.

**Comment by jxnblk** [comment]
Thanks for looking into this, but I don't think pinning the version is a great solution here. If you need to pin to a specific version, you can use yarn resolutions. Closing this out for now

**Comment by karlhorky** [comment]
Hm, too bad. Yarn resolutions is not a great solution for beginners.

I think the amount of issues caused by new versions of Gatsby (there are a lot of them, almost every time I start a new Gatsby project, there's something new) should be a factor weighing in the direction of pinning.

**Comment by trevordmiller** [comment]
I agree with @karlhorky. There are many users not using npm. For example, we have almost 50 mdx-deck projects in our organization.

**Pull request closed without merging**
