### PR TITLE
Correct escape URL

### PR DESCRIPTION
**Pull request by signalwerk**

### CODE REVIEW

**Comment by jxnblk** [comment]
Sorry for the delay. This shouldn't be necessary. If you have a use-case where the current implementation does not work, please provide a reproducible example and update the snapshots

**Comment by signalwerk** [comment]
@jxnblk it's too long ago to remember my correct example where it broke. But since the [spec](https://www.w3.org/TR/CSS21/syndata.html#uri) tells us that the URL is valid without the quotation marks you are right. but an image name with `page 2.jpg` is way more likely than `page"2.jpg` I still think my pull request is not bloated with two bytes and then people can use a space in their image-names. That was most likely also my case.

**Comment by jxnblk** [comment]
The space should stay intact in the js string in that example though, shouldn’t it?

**Comment by signalwerk** [comment]
@jxnblk no. it's not working when a space is in the filename.

**Pull request closed without merging**
