### PR TITLE
Add badge to display install size

### PR DESCRIPTION
**Pull request by styfle**
This adds a badge to the `README.md` to display the npm install size

### CODE REVIEW

**Comment by jxnblk** [comment]
Since this is a dev/build tool, it's not really intended to be installed in other applications. I don't think it makes sense to advertise that this is a (necessarily) massive CLI install

**Comment by styfle** [comment]
There is at least one other person who cares about the install size of their tools: https://github.com/styfle/packagephobia/issues/218

I realize it's not a goal but I'm trying to bring awareness because I don't believe there is any other way for users to know the size of `mdx-deck` before installing.

**Comment by Siilwyn** [comment]
Yes! I like my dev/build tools lightweight too, the 360MB install size is definitely a bummer and good to know beforehand.

**Comment by Siilwyn** [comment]
Btw. this is very much related to: #157

**Comment by jxnblk** [comment]
v2 has removed the `puppeteer` dependency from the core CLI, which should substantially reduce the install size. I took another look at this PR and it seems like the image link is either broken or *extremely* slow. I'm going to close this out for now

**Comment by styfle** [comment]
The badge is probably timing out when installing all the dependencies.

|version | install size |
|-------:|--------------|
| 1.8.2 | [install size](https://packagephobia.now.sh/result?p=mdx-deck@1.8.2) |
| 2.0.0-8 | [install size](https://packagephobia.now.sh/result?p=mdx-deck@2.0.0-8) |

Once you publish v2 as `latest` to npm, it will work nicely 👍

**Pull request closed without merging**
