### PR TITLE
Adds Button to go to normal view in presenter mode

### LINKED ISSUE #81: Open new window button in presenter mode
In presenter mode, there should be a button that opens a new window (that's not in presenter mode) that can be used to display the audience.

### PR DESCRIPTION
**Pull request by SaraVieira**
closes #81

Example: https://site-fimspttruq.now.sh/

### CODE REVIEW

**Comment by jxnblk** [comment]
Thanks! Do you mind removing the yarn.lock file or merging in master to clean up the diff?

**Comment by jxnblk** [comment]
No rush! Just triaging issues – this isn't holding up any particular release or anything like that

**Comment by SaraVieira** [comment]
Updated :D

**Comment by jxnblk** [comment]
Sorry for the delay, this looks great, thanks!

**Pull request merged**
