### PR TITLE
v3

### LINKED ISSUE #383: MDX Deck v3
I haven't had as much time to work on MDX Deck lately, so I wanted to document some of the upcoming changes I'd like to introduce in the next major version. A rough prototype was started on the [next](https://github.com/jxnblk/mdx-deck/tree/next/) branch for reference.

The high-level proposed changes are:

- Replace the core MDX Deck CLI with Gatsby
- Use `@mdx-deck/gatsby-theme` as the core part of the app
- Render each slide as static HTML (currently slides are client-side rendered)
- Enable shadowing of the core UI components (Provider, presenter view, etc)
- Allow any relevant Gatsby plugin to work with MDX Deck
- Replace custom theming setup with [Theme UI](https://theme-ui.com)
- Deprecate the use of default exports for layouts in favor of the approach here: #326
- The end-user API for authoring decks should be mostly backwards-compatible

I'm opening this issue to allow for discussion, and to gauge interest if anyone would like to help contribute to working towards the next major version of MDX Deck.

### PR DESCRIPTION
**Pull request by jxnblk**
- [x] Rewritten as a Gatsby theme (currently `gatsby-theme-mdx-deck`)
- [x] Any component can be shadowed
- [x] Deprecate & remove current Gatsby theme #394
- [x] Deprecate html-plugin #394
- [x] Deprecate mdx-plugin #394
- [x] Deprecate loader #394
- [x] Deprecate layouts package #394
- [x] Deprecate components package #394
- [x] New CLI powered by Gatsby #393
- [x] Updated theming to use [Theme UI][] #395
- [x] Add Gatsby starter #396
- [x] Add `eject` script to CLI
- [x] Update create-deck package
- [x] Add static `/print` route pages
- [x] Update export command/CLI
- ~~Aspect ratio support~~
- [x] Migration guide
- [x] Update Readme
- [x] Update docs
- [x] Add docs for Gatsby usage 
- [x] Update tests

Fixes #383 

[theme ui]: https://theme-ui.com

### CODE REVIEW

**Comment by marcysutton** [comment]
What a boss! Thanks for working on this!

**Comment by marcysutton** [comment]
Also: does this change mean that mdx-deck requires Gatsby? If so, it would help to make that explicit on the landing page–I think the README still needs to be updated.

**Comment by jxnblk** [comment]
> does this change mean that mdx-deck requires Gatsby, or just the theme?

The `mdx-deck` package, which includes the CLI, uses Gatsby under the hood, but it's a hard dependency and should work without installing Gatsby separately. I'm guessing you'll want to use `gatsby-theme-mdx-deck` to customize the site a little more, which should work like the previous Gatsby theme.

That said, there could definitely be some bugs, but your setup looks okay afaict

**Comment by marcysutton** [comment]
Good to know, thanks! I tried using `gatsby-theme-mdx-deck` but had to roll back when the path issues didn't work (I have too little time left to still be debugging slides rendering at all!) The layouts aren't working for me in the older release either, but I can work around that.

**Pull request merged**
