### PR TITLE
fix: keyboard controls after clicking button or link

### PR DESCRIPTION
**Pull request by aleclarson**
Links and buttons shouldn't prevent keyboard navigation.

### CODE REVIEW

**Comment by jxnblk** [comment]
This is to ensure the space bar can click buttons. I think if an element is focused on the page, it’s expected that the keyboard navigation won’t work

**Comment by aleclarson** [comment]
Maybe there should be an option to disable it via the theme or something?

Personally, I don't need spacebar to trigger buttons during my speech.

**Comment by Diazgin** [comment]
This is to ensure the space bar can click buttons. I think if an element is focused on the page,,

**Comment by jxnblk** [comment]
Thanks for working on this, but I think since this could break the behavior in some existing decks, this should be tabled for discussion in an issue and potentially addressed in the next major version

**Pull request closed without merging**
